name: mlm
channels:
  - bioconda
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - expat=2.7.1
  - libffi=3.4.4
  - libzlib=1.3.1
  - openssl=3.0.18
  - pip=25.2
  - python=3.10.19
  - setuptools=80.9.0
  - sqlite=3.50.2
  - tk=8.6.15
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - click==8.3.0
      - colorama==0.4.6
      - numpy==2.2.6
      - pandas==2.3.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - six==1.17.0
      - tzdata==2025.2
prefix: C:\Users\BiroB\AppData\Local\anaconda3\envs\mlm
